apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: MySQL
    type: mysql
    access: proxy
    url: mysql:3306
    database: xiuxian_game
    user: xiuxian
    secureJsonData:
      password: xiuxian123
    editable: true
